### ISSUE TITLE
Enhance the fgdc2HTML XSLT

### ISSUE THREAD

**Issue by eliotjordan** [OpenGeoMetadata/GeoCombine#102]
- There are a few errors in the fgdc2HTML file
- Transform some additional elements
- More completely test the output

**Comment by dl-maura** [comment]
@eliotjordan Do we have it documented somewhere what the errors are? looks like the additional elements was taken care of in a different ticket.

**Comment by eliotjordan** [comment]
@dl-maura https://github.com/OpenGeoMetadata/GeoCombine/pull/103 should close this ticket. According to the PR (it's been so long I don't remember them exactly):

- bug with FGDC supplemental information
- bug with contact person
- bug with FGDC voice, fax, email, house, and contact
