### ISSUE TITLE
Update logic for 'all repos' cloning/indexing tasks

### ISSUE THREAD

**Issue by dl-maura** [OpenGeoMetadata/GeoCombine#119]
Currently, the logic for indexing when no specific repo is specified is to pull all repositories with edu.*, uk.*, or org.* and anything in the allowlist (currently only big10). If orgs have made their repositories and didn't follow this, they are being excluded. The proposal is to either

1) Default to indexing everything unless it is on a deny list (don't do the explicit allow check)
2) Implement a tagging system where a repository whose owner would like it included uses the tag 'datasource'
    * Note that if we use tags we'll need to ask everyone to tag their repositories to maintain existing functionality

**Comment by dl-maura** [comment]
Did we end up choosing what we wanted to do here? Options 1 and 3 are pretty similar (1 being in code, 3 being a tag for the opengeo tools), I think 2 could easily be missed by new people adding their metadata repos for the first time

**Comment by karenmajewicz** [comment]
What do we mean by adding a tag? Where would that go?

**Comment by dl-maura** [comment]
I know you can add a tag when you create a release, I don't know if there is another tag system I'm unaware of.

If there isn't I think the easiest is a deny list, since it's such a small fraction of the stuff in the repository, I don't think it would be a ton of overhead to maintain (it is just going to be the tools and website, essentially). Then we aren't asking random metadata repo creators to learn GitHub tags.

**Comment by dl-maura** [comment]
Per meeting today, moving forward with deny list
