### ISSUE TITLE
Invalid ENVELOPE in `solr_geom` field in iso2geoBL.xsl

### ISSUE THREAD

**Issue by waynegraham** [OpenGeoMetadata/GeoCombine#15]
Currently the `ENVELOPE` generated for the `solr_geom` field is invalid and throws an exception in Solr.

https://github.com/OpenGeoMetadata/GeoCombine/blob/master/lib/xslt/iso2geoBL.xsl#L465-L487

This should be in the format

`ENVELOPE(minX, maxX, maxY, minY)`

**Comment by kimdurante** [comment]
Thanks Wayne!
I updated the xsl here:
https://github.com/geoblacklight/geoblacklight-schema/blob/master/lib/xslt/iso2geoBL.xsl

in an attempt to fix this issue and #14. When you get a chance, can you check to see if that works for you?

**Comment by waynegraham** [comment]
Hi Kim,

Thanks! I should have assigned them to me, they were notes for when I could get to them, but it looks like you beat me. I'll get @mossiso to take a look...

Wayne

**Comment by drh-stanford** [comment]
fixed in PR #16

**Comment by drh-stanford** [comment]
fixed
