### ISSUE TITLE
Better handling for records that fail to index

### ISSUE THREAD

**Issue by thatbudakguy** [OpenGeoMetadata/GeoCombine#168]
When a record fails to index, the cause could be one of a number of things:

- the record is invalid, and solr rejects it for not matching the schema
- the http request failed or was interrupted
- we made too many requests to solr and got blocked or throttled

In all of these cases, it'd be better to log the failure and continue on – currently indexing just stops. In some of them, it might also be useful to retry the request (possibly after a delay) using `faraday-retry` or similar.

**Comment by srappel** [comment]
This made indexing much less frustrating and the info output is much easier to understand. Thanks @thatbudakguy !
