### ISSUE TITLE
Batch indexing ends up dropping a document each iteration

### ISSUE THREAD

**Issue by spilth** [OpenGeoMetadata/GeoCombine#172]
While upgrading to GeoCombine 0.9.1 I was surprised to notice our 4202 documents only indexing a total of 4161. If I changed this number to 2000, only 1981 documents were indexed.

After digging into the code I discovered a document is being dropped each time the BATCH_SIZE is reached: https://github.com/OpenGeoMetadata/GeoCombine/blob/main/lib/geo_combine/indexer.rb#L42

It might be worth switching to using `.each_slice` instead of manually slicing the docs up.

**Comment by thatbudakguy** [comment]
resolved by #173
