### ISSUE TITLE
Possible XSL FGDC and ISO to HTML

### ISSUE THREAD

**Issue by mejackreed** [OpenGeoMetadata/GeoCombine#18]
So I found this XSL which actually seems to do a decent semantic job of going to HTML for both FGDC and HTML.

https://github.com/Esri/geoportal-server/blob/0b925c81ceb0d48474d0e78276c7e9546266e9fd/geoportal/src/gpt/search/profiles/metadata_to_html_full.xsl

See two sample conversion here: 

https://gist.github.com/mejackreed/2f9d78df58c61bf5c392

For ISO md I would like some better dt's but its not that terrible

Thoughts @gravesm , @drh-stanford , @eliotjordan , @kimdurante ??

**Comment by gravesm** [comment]
It's kind of an abuse of dl, since there's not a single dd in there. I'm not super keen on the fact that the key/value pairs end up as: `<em>key</em> value`. Still, this is not a high priority feature for me, so if it makes it easier to use this, I'm fine with it. It's probably good enough for how often this will be used.

**Comment by mejackreed** [comment]
I'm wondering if some of that could be slightly modified to remove the `<em>` in favor of just a `dt` and outside of that `dt` using the `dd` block. Not sure how hard that modification would be.

**Comment by kimdurante** [comment]
As Mike mentioned, it's probably good enough. However, particularly with ISO, I am not in favor of hierarchical element names and data types being presented in this way. For instance:

(identifier):
(MD_Identifier):
(code):
(CharacterString):http://purl.stanford.edu/wx587tc1912

could be represented more simply as:
Identifier: http://purl.stanford.edu/wx587tc1912

it just looks cleaner and given the hierarchy of ISO, would make the metadata more human readable to someone who doesn't have knowledge of the tag jargon.

**Comment by jrgriffiniii** [comment]
As https://github.com/OpenGeoMetadata/GeoCombine/pull/22 was understood to only partial address this issue, I am currently working to resolve https://github.com/geoblacklight/geoblacklight/issues/173.  Please note that there is still a discrepancy between the markup generated using these XSL Stylesheets and what styling is possible without hard-coding Bootstrap classes.  The desired design:

![](https://cloud.githubusercontent.com/assets/1656824/5256028/c99bb392-7977-11e4-98b1-5ed9c1f38a6b.jpg)

...and the currently supported implementation:

![geoblacklight_issues_173_screenshot](https://user-images.githubusercontent.com/1443986/28846057-06385cc8-76d8-11e7-8a99-6085c526f92b.png)

I'm afraid that I cannot implement the current design without modifying the XSL Stylesheets.  Are there any objections, thoughts, or additional changes which should be considered?

**Comment by mejackreed** [comment]
I'd say implement what is currently there (no XSL modifications) and then we can iterate on that. I'd be a bit hesitant to provide custom styling in GeoCombine, but I could see that getting injected by consumers of GeoCombine using Nokogiri later down the line.

**Comment by thatbudakguy** [comment]
Closing, since these XSL exist now
