### ISSUE TITLE
JSON object for Solr

### ISSUE THREAD

**Issue by waynegraham** [OpenGeoMetadata/GeoCombine#25]
As the `iso2geoBL.xsl` file stands, it generates the Solr doc content, but the default update handler (at least in the version of Solr) expects the same `add` and `doc` as the XML. 

```json
{ 
"add": {
  "doc": {
            "uuid": ""
            ...
        }
    }
}
```

**Comment by mejackreed** [comment]
Is the idea here that the json should have the add and doc keys?

**Comment by waynegraham** [comment]
It's not clearly documented, but https://wiki.apache.org/solr/UpdateJSON#Update_Commands suggests that each document needs the `add` and `doc` keys. We ran in to this issue posting these to Solr and wrapping the content in `add` and `doc` resolved the issue.

**Comment by mejackreed** [comment]
Ahh... gotcha. Maybe that could be added as an additional type? Indexing with RSolr wraps this up without needing the add/doc keys.

Also I believe Solr  > 4 this is isn't needed anymore with the atomic updates. I might be wrong though.. @cbeer can you weigh in?

**Comment by waynegraham** [comment]
I think we need to debug on our end a bit further; RSolr was failing to wrap the add/doc and was throwing exceptions...

Our current workaround is to inject the add/doc keys with `sed` :hammer:
