### ISSUE TITLE
Auto-generate solr_ fields for GeoBlacklight conversions

### ISSUE THREAD

**Issue by drh-stanford** [OpenGeoMetadata/GeoCombine#5]
When converting from ISO/FGDC into GeoBlacklight, all of the `solr_` Solr schema fields should be auto-generated from their authorative elements.

See the "Implementation" section here for the list of Solr fields:

  http://journal.code4lib.org/articles/9710

In the latest version of GeoBlacklight, we've cut the fields down to `solr_geom`, `solr_year_i`, and `solr_issued_dt`

**Comment by thatbudakguy** [comment]
I think this has been done for awhile.
