### ISSUE TITLE
Don't know how to build task 'geocombine:index'

### ISSUE THREAD

**Issue by supritasrinivas** [OpenGeoMetadata/GeoCombine#64]
Hello GeoCombine Dev

#### Summary
Sitting at the Geo4LibCamp 2017 working through a tutorial on getting bulk data from geocombine, I ran into the issue above. 
* Downloaded zip file from [Stanford](https://github.com/OpenGeoMetadata/edu.stanford.purl)
* Unzipped the file
* Added `gem geo_combine` to my Gemfile
* Ran `bundle install`
* Tried running `bundle exec rake geocombine:index` and hit the `Don't know how to build task 'geocombine:index'` error.
* grepped for geocombine rake tasks and did not find any
```
be rake -T| grep geo_combine
be rake -T| grep geocombine
```

**Comment by egspoony** [comment]
I installed geo_combine as a gem on my computer then ran
`geocombine index`

This worked as long as your data was in the right place.

**Comment by supritasrinivas** [comment]
@egspoony was there a way to pass the location of the file with data as an argument?

**Comment by egspoony** [comment]
> Will clone all edu.* OpenGeoMetadata repositories into ./tmp/opengeometadata. Location of the OpenGeoMetadata repositories can be configured using the OGM_PATH environment variable.

`$ OGM_PATH='my/custom/location' rake geocombine:clone`

I think if you set the environmental variable OGM_PATH then run `geocombine index` I am hoping this will work.

**Comment by mejackreed** [comment]
Thanks @supritasrinivas, I was able to replicate the problem locally too! It looks like the rake tasks are not being loaded up for some reason.

**Comment by drh-stanford** [comment]
I had this problem too -- not sure why the rake task isn't loading by default. The workaround is to put this in your `Rakefile`:

```ruby
spec = Gem::Specification.find_by_name 'geo_combine'
load "#{spec.gem_dir}/lib/tasks/geo_combine.rake"
```
